[package]
name = "socket"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["net", "macros", "rt-multi-thread", "sync", "io-util"] }
